basePath: /api/
definitions:
  main.Labware:
    properties:
      name:
        type: string
      wells:
        items:
          $ref: '#/definitions/main.Well'
        type: array
      zDimension:
        description: |-
          XDimension float64 `json:"xDimension"` // Microplate: 127.76
          YDimension float64 `json:"yDimension"` // Microplate: 85.48
        type: number
    type: object
  main.Message:
    properties:
      message:
        type: string
    type: object
  main.Well:
    properties:
      address:
        type: string
      depth:
        type: number
      diameter:
        type: number
      x:
        type: number
      "y":
        type: number
      z:
        type: number
    type: object
info:
  contact: {}
  description: The Ammonite API interface.
  title: Ammonite API
  version: "0.1"
paths:
  /labwares:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Labware'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get all labwares
      tags:
      - labware
  /labwares/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Labware
        in: body
        name: labware
        required: true
        schema:
          $ref: '#/definitions/main.Labware'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create one labware
      tags:
      - labware
  /labwares/{name}:
    delete:
      parameters:
      - description: Labware name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Delete one labware
      tags:
      - labware
    get:
      parameters:
      - description: Labware name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Labware'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get one labware
      tags:
      - labware
  /ping:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Message'
      summary: A pingable endpoint
      tags:
      - dev
  /protocol:
    post:
      consumes:
      - application/json
      parameters:
      - description: commandInput
        in: body
        name: collection
        required: true
        schema:
          items: {}
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Run a protocol
      tags:
      - protocol
swagger: "2.0"
