basePath: /api/
definitions:
  main.Deck:
    properties:
      calibrated:
        type: boolean
      locations:
        items:
          $ref: '#/definitions/main.Location'
        type: array
      name:
        type: string
      x:
        type: number
      "y":
        type: number
      z:
        type: number
    type: object
  main.InputDeck:
    properties:
      locations:
        items:
          $ref: '#/definitions/main.Location'
        type: array
      name:
        type: string
    type: object
  main.Labware:
    properties:
      name:
        type: string
      wells:
        items:
          $ref: '#/definitions/main.Well'
        type: array
      zDimension:
        description: |-
          XDimension float64 `json:"xDimension"` // Microplate: 127.76
          YDimension float64 `json:"yDimension"` // Microplate: 85.48
        type: number
    type: object
  main.Location:
    properties:
      name:
        type: string
      x:
        type: number
      "y":
        type: number
      z:
        type: number
    type: object
  main.Message:
    properties:
      message:
        type: string
    type: object
  main.Well:
    properties:
      address:
        type: string
      depth:
        type: number
      diameter:
        type: number
      x:
        type: number
      "y":
        type: number
      z:
        type: number
    type: object
info:
  contact: {}
  description: The Ammonite API interface.
  title: Ammonite API
  version: "0.1"
paths:
  /deck/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Deck
        in: body
        name: deck
        required: true
        schema:
          $ref: '#/definitions/main.InputDeck'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create one deck
      tags:
      - deck
  /deck/{name}:
    delete:
      parameters:
      - description: Deck name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Delete one deck
      tags:
      - deck
    get:
      parameters:
      - description: Deck name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Deck'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get one deck
      tags:
      - deck
  /deck/{name}/{x}/{y}/{z}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Deck name
        in: path
        name: name
        required: true
        type: string
      - description: X coordinate
        in: path
        name: x
        required: true
        type: number
      - description: Y coordinate
        in: path
        name: "y"
        required: true
        type: number
      - description: Z coordinate
        in: path
        name: z
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Calibrate a deck
      tags:
      - deck
  /decks:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Deck'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get all decks
      tags:
      - deck
  /labware/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Labware
        in: body
        name: labware
        required: true
        schema:
          $ref: '#/definitions/main.Labware'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create one labware
      tags:
      - labware
  /labware/{name}:
    delete:
      parameters:
      - description: Labware name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Delete one labware
      tags:
      - labware
    get:
      parameters:
      - description: Labware name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Labware'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get one labware
      tags:
      - labware
  /labwares:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Labware'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get all labwares
      tags:
      - labware
  /ping:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Message'
      summary: A pingable endpoint
      tags:
      - dev
swagger: "2.0"
